# Use Node.js image
FROM node:14

# Set the working directory to /app inside the container
WORKDIR /app

# Copy package.json and package-lock.json to /app
COPY package.json ./
COPY package-lock.json ./

# Install the dependencies
RUN npm install

# Copy the rest of your backend files
COPY . .

# Expose port 5000 for the backend
EXPOSE 5000

# Command to run your backend
CMD ["node", "server.js"]
